"""Initial migration

Revision ID: acbb413308a4
Revises: 
Create Date: 2026-05-23 15:30:14.907505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'acbb413308a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercise', 'equipment_needed',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text('\'"None"\'::character varying'))
    op.alter_column('exercise', 'muscles',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('exercise', 'external_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercise', 'external_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('exercise', 'muscles',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('exercise', 'equipment_needed',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text('\'"None"\'::character varying'))
    # ### end Alembic commands ###
